services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.0
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_LOG_PREFIX=${S3_LOG_PREFIX}
      - ENDPOINT_URL=${ENDPOINT_URL}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
    
    networks:
      - elk-networks

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.14.0
    env_file:
      - ./.env
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
    networks:
      - elk-networks

networks:
  elk-networks:
    external: True