services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_networks

  pushgateway:
    container_name: gateway
    image: prom/pushgateway
    ports:
      - "9091:9091"
    networks:
      - monitoring_networks


  grafana:
    container_name: grafana-dashboards
    image: grafana/grafana
    env_file:
      - ./.env
    environment:
      GF_DASHBOARDS_MIN_REFRESH_INTERVAL: 500ms
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - monitoring_networks

networks:
  monitoring_networks:
    external: true

