services:
  proxy:
    container_name: monitoring_proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - monitoring_networks
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd

networks:
  monitoring_networks:
    external: true